### ISSUE TITLE
Prompted to update on start

### ISSUE THREAD

**Issue by mhughson** [michel-iwaniec/bb-studio#1]
When booting up BBStudio, I am prompted to update. Hitting the update button takes me to the GBStudio website.

**Comment by michel-iwaniec** [comment]
Thanks for the bug report! The update has been disabled in https://github.com/michel-iwaniec/bb-studio/commit/5c058ae8ad2c0a2714f2fbd0fab49c21d8cd4fd1 to avoid confusion.

An automated non-release build with the fix is available here: https://github.com/michel-iwaniec/bb-studio/actions/runs/12214065175

Let me know if there's any outstanding issues with updates - otherwise I'll close the ticket.
