### ISSUE TITLE
Background and sprites don't display properly in exported ROM when System Compatibility is set to "Color Only".

### ISSUE THREAD

**Issue by TVS-Official-64** [michel-iwaniec/bb-studio#3]
**Description:**
Both the background and the sprites appear glitched upon loading the game. Upon loading, the last 128 tiles of the background's CHR are taken up by dialogue boxes, and all active sprites appear glitched.

**How to reproduce the problem:**
1. Create a 256x240 background using your preferred software (preferably one that takes up more than 128 tiles).
2. Add your background to BB Studio.
3. Go to your project settings and set System Compatibility to _"Color Only"_
4. Export the ROM 
5. Open the exported ROM in a compatible emulator. At this point you should see the graphical issues occur on both the background and sprites.

**Expected Behavior:**
What was supposed to happen was the entire background would've been displayed properly, with the dialogue boxes being displayed in an entirely different CHR bank. Additionally, the sprites would've displayed properly.

![game_001](https://github.com/user-attachments/assets/9ccbbb2c-5740-4c43-838c-d0de8a3efd4d)
![CHR_Result](https://github.com/user-attachments/assets/9c26f12c-3482-485c-8e74-f05e0271a378)

Image 1: The issue in action. Note how the player sprite appears very glitched.
Image 2: The current CHR while this issue is occurring

 - OS: Windows 11
 - App version: Alpha Build 1 (prerelease)

**Comment by michel-iwaniec** [comment]
Thank you for pointing this out.

The core reason for the bug is that colorOnly mode essentially switches the background compiler code to use a 9th bit of tile index in the GBC - a feature the NES doesn't have.

Thinking about this, it makes little sense to have the three different modes ("mono", "mixed" and "colorOnly") in BB Studio. Maybe in the future we could use the setting for imported project to indicate that slower CPU speed is acceptable and palette handling redundant. But for the moment I think this setting only causes confusion.

So for now, I've removed it in my latest source commit. Essentially my latest change does the following:
* The setting is hidden in the settings page
* When loading a project, the project setting is overridden to be "mixed"

I believe this should fix the issue. Let me know if there are still problems!

There is a separate issue that at least logo backgrounds should be able to use more than 256 tiles. But this can be achievable with CHR-RAM bank-switching using interrupts rather than the (non-existent) 9th bit for tile indices.
